name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Build with Maven
        run: mvn package -Dmaven.test.skip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"


      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_KEY }}
            source: "target/*.jar"
            target: "/home/ec2-user/"

      - name: SSH and Restart Application
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_KEY }}
            script: |
                echo "Stopping existing Java process if any..."
                PID=$(ps -ef | grep 'java -jar' | grep -v grep | awk '{print $2}')
                if [ -n "$PID" ]; then
                  echo "Found Java process with PID: $PID"
                  kill -TERM $PID
                  sleep 2  # Allow some time for the process to terminate
                else
                  echo "No existing Java process found."
                fi

                echo "Starting new Java process..."
                nohup java -jar /home/ec2-user/target/filestorage.jar > /home/ec2-user/app.log 2>&1 &
                sleep 5  # Allow some time for the process to start

                echo "Checking if the process started successfully..."
                if ps -ef | grep -q '[j]ava -jar'; then
                  echo "Java process started successfully."
                else
                  echo "Failed to start Java process."
                  exit 1
                fi